name: build
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_call:
    inputs:
      tag-name:
        required: true
        type: string
    outputs:
      image_tags:
        value: ${{ jobs.image.outputs.image_tags }}
      image_url:
        value: https://ghcr.io/${{ github.repository }}

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAMESPACE: ${{ github.repository_owner }}
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  env:
    # release-please によるコミットの時は workflow_call でのみ実行する
    if: ${{ !( github.workflow == 'build' && startsWith(github.event.head_commit.message, 'release:') && github.event.head_commit.author.name == 'eoeo-release[bot]' ) }}
    runs-on: ubuntu-latest
    outputs:
      BINARY_NAME: ${{ steps.meta.outputs.BINARY_NAME }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - id: meta
        run: |
          echo "BINARY_NAME=$(cargo metadata --offline --no-deps --format-version=1 | jq -r '.packages[].targets[] | select(.kind | map(. == "bin") | any ) | .name')" >> $GITHUB_OUTPUT

  build:
    needs: [env]
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        profile: ${{ github.ref_name == github.event.repository.default_branch && fromJson('["dev", "release"]') || fromJson('["dev"]') }}
        platform:
          - target: aarch64-unknown-linux-musl
            os: ubuntu-24.04-arm
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
    runs-on: ${{ matrix.platform.os }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
    defaults:
      run:
        shell: bash -xe {0}
    steps:
      - name: Install musl tools
        if: ${{ endsWith(matrix.platform.target, '-unknown-linux-musl') }}
        run: |
          echo 'set man-db/auto-update false' | sudo debconf-communicate
          sudo dpkg-reconfigure man-db
          sudo apt-get install -y musl-tools --no-install-recommends
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          filter: tree:0
          fetch-depth: 0
      - run: |
          rustup target add ${{ matrix.platform.target }}
      - uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # v2.7.7
        with:
          key: ${{ matrix.profile }}-${{ matrix.platform.target }}
      - run: mkdir dist/
      - run: |
          cargo build --locked --bins --artifact-dir=dist -Z unstable-options ${{ matrix.profile == 'release' && '--release' || '' }} --target=${{ matrix.platform.target }}
      - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: ${{ matrix.profile }}-${{ matrix.platform.target }}
          path: |
            dist/${{ needs.env.outputs.BINARY_NAME }}
            dist/${{ needs.env.outputs.BINARY_NAME }}.exe
          if-no-files-found: error
      - name: Upload to release
        if: ${{ inputs.tag-name && matrix.profile == 'release' }}
        working-directory: dist/
        run: |
          if [ -e ${{ needs.env.outputs.BINARY_NAME }}.exe ]; then
            filename="${{ needs.env.outputs.BINARY_NAME }}-${{ inputs.tag-name }}-${{ matrix.platform.target }}.exe"
            mv ${{ needs.env.outputs.BINARY_NAME }}.exe "$filename"
            gh release upload ${{ inputs.tag-name }} "$filename"#${{ matrix.platform.target }} --clobber
          else
            filename="${{ needs.env.outputs.BINARY_NAME }}-${{ inputs.tag-name }}-${{ matrix.platform.target }}"
            mv ${{ needs.env.outputs.BINARY_NAME }} "$filename"
            gh release upload ${{ inputs.tag-name }} "$filename"#${{ matrix.platform.target }} --clobber
          fi
  image:
    needs: [env, build]
    if: ${{ github.event_name != 'pull_request' && github.ref_name == github.event.repository.default_branch }}
    permissions:
      packages: write
    runs-on: ubuntu-latest
    outputs:
      image_tags: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
        with:
          path: artifact
          pattern: release-*-unknown-linux-musl

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
        with:
          images: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=${{ inputs.tag-name }}
            type=semver,pattern={{major}}.{{minor}},value=${{ inputs.tag-name }}
            type=semver,pattern={{major}},value=${{ inputs.tag-name }}
            type=edge
            type=ref,event=branch

      - name: Build Images
        run: |
          build() {
            newcontainer=$(buildah from --platform="$1" scratch)
            buildah copy --chmod=0755 $newcontainer ./artifact/release-"$2"/${{ needs.env.outputs.BINARY_NAME }} /${{ needs.env.outputs.BINARY_NAME }}
            buildah config --entrypoint='["./${{ needs.env.outputs.BINARY_NAME }}"]' $newcontainer

            buildah config --author="Mogyuchi" $(awk '{print "--label=" $0}' <<< "${{ steps.meta.outputs.labels }}") $newcontainer
            buildah inspect $newcontainer

            buildah commit --manifest=localhost/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }} $newcontainer
            buildah rm $newcontainer
          }
          build linux/amd64 x86_64-unknown-linux-musl
          build linux/arm64 aarch64-unknown-linux-musl

      - name: Push To GHCR
        run: |
          buildah manifest inspect localhost/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}
          tac <<< '${{ steps.meta.outputs.tags }}' \
          | parallel --halt=now,fail=1 --jobs=1 'buildah --log-level=trace manifest push --creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} --all --digestfile="$RUNNER_TEMP/image-digest" localhost/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }} docker://{} && printf "\`\`\`\n%s@$(cat "$RUNNER_TEMP/image-digest")\n\`\`\`\n" {} >> "$GITHUB_STEP_SUMMARY"'
